name: color_vision_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.33.0+43
environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.12.0+1
  image_picker: ^1.2.2
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  device_info_plus: ^10.1.0
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter_native_splash:
  color: "#000000"
  image: "assets/images/splash_logo.png"
  android_12:
    image: "assets/images/splash_logo.png"
    color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
